
export enum NotificationType {
    NEW_COMPATIBLE_VACANCY = 'NEW_COMPATIBLE_VACANCY',
    NEW_APPLICATION = 'NEW_APPLICATION',
    APPLICATION_SUCCESSFULLY_REGISTERED = 'APPLICATION_SUCCESSFULLY_REGISTERED',
    INTERNSHIP_CREATED_STUDENT = 'INTERNSHIP_CREATED_STUDENT',
    INTERNSHIP_CREATED_UNIVERSITY = 'INTERNSHIP_CREATED_UNIVERSITY'
}